### ISSUE TITLE
Implement initial sm4t-container 

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/sm4t-container#1]
## Summary

Implement a Docker container to run SeamlessM4T models for multimodal translation.

## Tasks

- [ ] Create Dockerfile
  - Use Python base image
  - Install SeamlessM4T and dependencies
- [ ] Copy SeamlessM4T code into image
- [ ] Create entrypoint script
  - Import SeamlessM4T and start Python shell
- [ ] Include base SeamlessM4T models
  - S2ST, S2TT, T2ST, T2TT  
- [ ] Create data volume
  - For caching downloaded models
- [ ] Write README
  - Overview
  - Usage
  - Models
  - Volumes
  
## Requirements

- Dockerfile builds image with SeamlessM4T installed
- Entrypoint launches Python shell with SeamlessM4T imported 
- Base SeamlessM4T models included
- Data volume for caching models
- README explains usage and configs

## Resources

- SeamlessM4T repo: https://github.com/facebookresearch/seamless_communication
